// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[bookId]" | "/[bookId]/[chapterNum]" | "/[bookId]/contents" | "/auth-callback" | "/library" | "/profile"
type AppRouteHandlerRoutes = "/api/annotations" | "/api/annotations/[id]" | "/api/audio/[...path]" | "/api/auth/google-callback" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/magic-link" | "/api/auth/me" | "/api/auth/verify" | "/api/books" | "/api/books/[bookId]" | "/api/books/[bookId]/chapters/[chapterNum]" | "/api/chat/token" | "/api/progress" | "/api/user/history" | "/api/user/usage"
type PageRoutes = never
type LayoutRoutes = "/" | "/[bookId]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[bookId]": { "bookId": string; }
  "/[bookId]/[chapterNum]": { "bookId": string; "chapterNum": string; }
  "/[bookId]/contents": { "bookId": string; }
  "/api/annotations": {}
  "/api/annotations/[id]": { "id": string; }
  "/api/audio/[...path]": { "path": string[]; }
  "/api/auth/google-callback": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/magic-link": {}
  "/api/auth/me": {}
  "/api/auth/verify": {}
  "/api/books": {}
  "/api/books/[bookId]": { "bookId": string; }
  "/api/books/[bookId]/chapters/[chapterNum]": { "bookId": string; "chapterNum": string; }
  "/api/chat/token": {}
  "/api/progress": {}
  "/api/user/history": {}
  "/api/user/usage": {}
  "/auth-callback": {}
  "/library": {}
  "/profile": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[bookId]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
