#!/usr/bin/env python3
"""
Resize a book cover image into the two sizes required by the site.

Input:  public/covers/{book-id}.png   (generated by img.py)
Output:
  public/covers/{book-id}-lg.png   — full-res PNG (for book detail page)
  public/covers/{book-id}-sm.jpg   — 400px-wide JPG thumbnail (for library grid)

Usage:
    .venv/bin/python .claude/skills/curator/text/resize_cover.py --book-id {book-id}
    .venv/bin/python .claude/skills/curator/text/resize_cover.py --book-id {book-id} --input path/to/custom.png

Requires: Pillow
    .venv/bin/pip install Pillow
"""

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Pillow not installed. Run: .venv/bin/pip install Pillow")
    sys.exit(1)

PROJECT_ROOT = Path(__file__).resolve().parents[3]
COVERS_DIR = PROJECT_ROOT / "public" / "covers"

# Thumbnail width (height is computed to preserve aspect ratio)
THUMBNAIL_WIDTH = 400
# JPEG quality for thumbnails (0-95; 85 is a good default)
JPEG_QUALITY = 85


def resize_cover(book_id: str, input_path: Path = None) -> dict:
    """
    Resize a cover image into -lg.png and -sm.jpg.
    Returns paths of generated files.
    """
    if input_path is None:
        input_path = COVERS_DIR / f"{book_id}.png"

    if not input_path.exists():
        raise FileNotFoundError(f"Source image not found: {input_path}")

    lg_path = COVERS_DIR / f"{book_id}-lg.png"
    sm_path = COVERS_DIR / f"{book_id}-sm.jpg"

    img = Image.open(input_path).convert("RGB")
    w, h = img.size
    print(f"  Source: {input_path.name}  ({w}×{h})")

    # -lg: copy as PNG (no resize — keep full resolution)
    img.save(lg_path, format="PNG", optimize=True)
    print(f"  Saved: {lg_path.name}  ({lg_path.stat().st_size // 1024}KB)")

    # -sm: resize to THUMBNAIL_WIDTH wide, save as JPEG
    thumb_h = int(h * THUMBNAIL_WIDTH / w)
    thumb = img.resize((THUMBNAIL_WIDTH, thumb_h), Image.LANCZOS)
    thumb.save(sm_path, format="JPEG", quality=JPEG_QUALITY, optimize=True)
    print(f"  Saved: {sm_path.name}  ({sm_path.stat().st_size // 1024}KB)")

    return {"lg": str(lg_path), "sm": str(sm_path)}


def main():
    parser = argparse.ArgumentParser(description="Resize book cover to -lg.png and -sm.jpg")
    parser.add_argument("--book-id", required=True, help="Book ID (e.g. austen-emma)")
    parser.add_argument("--input", help="Custom source image path (default: public/covers/{book-id}.png)")
    args = parser.parse_args()

    input_path = Path(args.input) if args.input else None
    result = resize_cover(args.book_id, input_path)
    print(f"Done. Upload with: .venv/bin/python scripts/upload_to_gcs.py --covers --force")


if __name__ == "__main__":
    main()
