var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/auth-callback/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__99615fb6._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_82d61735._.js")
R.c("server/chunks/ssr/[root-of-the-server]__be8b90de._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__8a6d118e._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_auth-callback_page_actions_ad2bae9b.js")
R.m(89228)
module.exports=R.m(89228).exports
